headersOrigin = "config"
plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/silvioloma/Sito per Week"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*.html"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/img/*"

[headers.values]
Cache-Control = "public, max-age=604800, immutable"